import { NextRequest, NextResponse } from "next/server";
import { prisma, VerificationStatus, ServiceStatus } from "@mymail/database";

export const dynamic = "force-dynamic";

/**
 * GET /api/domains
 * Returns all domains with their mailboxes, aliases, and sending configs.
 */
export async function GET() {
  try {
    const domains = await prisma.domain.findMany({
      include: {
        mailboxes: {
          select: {
            id: true,
            localPart: true,
            address: true,
            displayName: true,
            status: true,
          },
        },
        aliases: {
          select: {
            id: true,
            address: true,
            targetMailboxId: true,
            enabled: true,
          },
        },
        sendingConfig: {
          include: {
            providerConnection: {
              select: {
                id: true,
                name: true,
                provider: true,
                status: true,
              },
            },
          },
        },
      },
      orderBy: { createdAt: "desc" },
    });

    return NextResponse.json({ domains });
  } catch (error: any) {
    console.error("Error fetching domains:", error);
    return NextResponse.json(
      { error: "Failed to fetch domains", details: error?.message },
      { status: 500 }
    );
  }
}

/**
 * POST /api/domains
 * Adds a new custom domain and generates required DNS guidance.
 */
export async function POST(req: NextRequest) {
  try {
    const body = await req.json();
    const { name } = body;

    if (!name || typeof name !== "string") {
      return NextResponse.json({ error: "Domain name is required" }, { status: 400 });
    }

    const domainName = name.toLowerCase().trim().replace(/^https?:\/\//, "").replace(/\/.*$/, "");

    // Get or create owner user
    let user = await prisma.user.findFirst();
    if (!user) {
      user = await prisma.user.create({
        data: {
          id: "00000000-0000-0000-0000-000000000001",
          email: "admin@example.com",
          name: "Default Admin",
        },
      });
    }

    // Required DNS records template
    const requiredDnsRecords = [
      {
        type: "MX",
        name: "@",
        value: "route1.mx.cloudflare.net",
        priority: 10,
        purpose: "Cloudflare Email Routing (Inbound)",
      },
      {
        type: "MX",
        name: "@",
        value: "route2.mx.cloudflare.net",
        priority: 20,
        purpose: "Cloudflare Email Routing (Inbound)",
      },
      {
        type: "MX",
        name: "@",
        value: "route3.mx.cloudflare.net",
        priority: 30,
        purpose: "Cloudflare Email Routing (Inbound)",
      },
      {
        type: "TXT",
        name: "@",
        value: "v=spf1 include:_spf.mx.cloudflare.net include:resend.com ~all",
        purpose: "SPF (Inbound Routing & Resend Outbound)",
      },
      {
        type: "TXT",
        name: "resend._domainkey",
        value: "p=MIGfMA0GCSqGSIb3DQEBAQUAA4GNADCBiQKBgQC... (generated by Resend)",
        purpose: "DKIM (Resend Outbound Delivery)",
      },
      {
        type: "TXT",
        name: "_dmarc",
        value: `v=DMARC1; p=none; rua=mailto:dmarc@${domainName}`,
        purpose: "DMARC Policy",
      },
    ];

    const domain = await prisma.domain.create({
      data: {
        name: domainName,
        ownerId: user.id,
        verificationStatus: VerificationStatus.VERIFIED,
        inboundStatus: ServiceStatus.ACTIVE,
        outboundStatus: ServiceStatus.ACTIVE,
        dnsRecords: requiredDnsRecords,
      },
    });

    return NextResponse.json({
      success: true,
      domain,
      dnsRecords: requiredDnsRecords,
    });
  } catch (error: any) {
    console.error("Error creating domain:", error);
    if (error?.code === "P2002") {
      return NextResponse.json({ error: "Domain already exists" }, { status: 409 });
    }
    return NextResponse.json(
      { error: "Failed to create domain", details: error?.message },
      { status: 500 }
    );
  }
}
